export { Checkboxs, type TCheckType } from "./src/controls/checkbox"
export { type CInputType, default as Input } from "./src/controls/input"
export { type CSelectType, default as Select } from "./src/controls/select"
export { default as Form, FormInside } from "./src/form"
export { FieldArrayForm } from "./src/render-array-form"
